# Generated by Django 5.1.5 on 2025-01-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='profiles.trainer')),
            ],
        ),
    ]
