# Generated by Django 5.1.5 on 2025-01-31 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='SportDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('vat_number', models.CharField(max_length=11, unique=True, verbose_name='Partita IVA')),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medici',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
            ],
            options={
                'verbose_name': 'Allenatore',
                'verbose_name_plural': 'Allenatori',
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('date_of_birth', models.DateField(verbose_name='Data di Nascita')),
                ('place_of_birth', models.CharField(max_length=150, verbose_name='Luogo di Nascita')),
                ('fiscal_code', models.CharField(max_length=16, unique=True, verbose_name='Codice Fiscale')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='athletes', to='profiles.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atleti',
            },
        ),
        migrations.CreateModel(
            name='HistoricAthleteTrainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historic_trainer_links', to='profiles.athlete')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historic_athlete_links', to='profiles.trainer')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='trainers',
            field=models.ManyToManyField(related_name='athletes', through='profiles.HistoricAthleteTrainer', to='profiles.trainer'),
        ),
    ]
