# Generated by Django 5.1.5 on 2025-02-03 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria Atleta', 'verbose_name_plural': 'Categorie Atleti'},
        ),
        migrations.AlterModelOptions(
            name='historicathletetrainer',
            options={'verbose_name': 'Storico Atleta Allenatore', 'verbose_name_plural': 'Storico Atleti Allenatori'},
        ),
    ]
